apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argus.fullname" . }}-collector
  namespace: {{ template "argus.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    helm-chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    helm-revision: "{{ .Release.Revision }}"
    ## keep value false as string, spinnaker's limitation, otherwise spinnaker fails to cast boolean to string
    strategy.spinnaker.io/versioned: "false"
    {{- include "argus.annotations" . | nindent 4 }}
data:
  collector-conf.yaml: |
    agentConf:
      {{- if not .Values.collector.disableLightweightCollector }}
      {{- $abc := include "trimmed-collector-config-agentConf" . | fromYaml }}
      {{- get $abc "trimmedCollectorAgentConf" | toYaml | nindent 6 }}
      {{- end }}
      {{- toYaml .Values.collector.collectorConf.agentConf | nindent 6 }}