{{- if .Values.rbac.create -}}
---
apiVersion: {{ template "lmutil.rbac.apiVersion" . }}
kind: ClusterRole
metadata:
  name: {{ include "lmutil.fullname" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}
    {{- if .Values.webhook.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        logicmonitor.com/aggregate-to-argus: "true"
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - containers
      - nodes
      - services
      - namespaces
      - componentstatuses
      - persistentvolumes
      - persistentvolumeclaims
      - secrets
      - endpoints
      - limitranges
      - resourcequotas
      - serviceaccounts
      - configmaps
    verbs:
      - list
      - get
      - watch
      - update
      - create
      - patch
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
        - mutatingwebhookconfigurations
    verbs:
        - get
        - patch
---
kind: ClusterRole
apiVersion: {{ template "lmutil.rbac.apiVersion" . }}
metadata:
  name: {{ include "lmutil.fullname" . }}-child
  namespace: {{ template "lmutil.release.namespace" . }}
  labels:
    logicmonitor.com/aggregate-to-argus: "true"
    {{- include "argus.labels" . | nindent 4 }}
  annotations:
    {{- include "argus.annotations" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
      - containers
      - nodes
      - services
      - namespaces
      - componentstatuses
      - persistentvolumes
      - persistentvolumeclaims
      - secrets
      - endpoints
      - limitranges
      - resourcequotas
      - serviceaccounts
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "storage.k8s.io"
    resources:
      - storageclasses
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - get
      - patch
      - watch
      - update
      - create
      - deletecollection
  - apiGroups:
      - "apps"
    resources:
      - deployments
      - deployments/scale
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - list
      - get
      - watch
      - update
      - patch
  - apiGroups:
      - "scheduling.k8s.io"
    resources:
      - priorityclasses
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "autoscaling"
    resources:
      - horizontalpodautoscalers
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "networking.k8s.io"
    resources:
      - networkpolicies
      - ingresses
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "rbac.authorization.k8s.io"
    resources:
      - clusterroles
      - clusterrolebindings
      - roles
      - rolebindings
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "batch"
    resources:
      - cronjobs
      - jobs
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "policy"
    resources:
      - poddisruptionbudgets
    verbs:
      - list
      - get
      - watch
      - update
  - apiGroups:
      - "apiextensions.k8s.io"
    resources:
      - customresourcedefinitions
    verbs:
      - list
      - get
      - watch
      - update
  - nonResourceURLs:
      - /
      - /healthz
      - /healthz/*
    verbs:
      - get
{{- if .Values.webhook.enabled }}
  # Additional permissions for webhook operations
  - apiGroups:
      - "admissionregistration.k8s.io"
    resources:
      - mutatingadmissionwebhookconfigurations
      - validatingadmissionwebhookconfigurations
    verbs:
      - list
      - get
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - update
      - patch
      - delete
{{- end }}
---
apiVersion: {{ template "lmutil.rbac.apiVersion" . }}
kind: ClusterRoleBinding
metadata:
  name: {{ include "lmutil.fullname" . }}
  namespace: {{ template "lmutil.release.namespace" . }}
{{- if .Values.labels}}
  labels:
{{ toYaml .Values.labels| indent 4 }}
{{- end }}
  annotations:
    {{- if .Values.webhook.enabled }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-15"
    "helm.sh/hook-delete-policy": before-hook-creation
    {{- end }}
    {{- if .Values.annotations }}
{{ toYaml .Values.annotations | indent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "lmutil.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "lmutil.serviceAccountName" . }}
    namespace: {{ template "lmutil.release.namespace" . }}
{{- end -}}
