{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lmutil.fullname" . }}-webhook
  namespace: {{ include "lmutil.release.namespace" . }}
  labels:
    {{ include "argus.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
  annotations:
    {{ include "argus.annotations" . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: webhook-api
      protocol: TCP
      name: webhook-api
  selector:
    {{ include "lmutil.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
