apiVersion: v2
description: Automated collector management
icon: https://logicmonitor.github.io/helm-charts-qa/lm_logo.png
kubeVersion: '>= 1.16.0-0'
maintainers:
  - email: argus@logicmonitor.com
    name: LogicMonitor
name: collectorset-controller
version: 4.3.0-rc05
home: https://logicmonitor.github.io/helm-charts-qa
appVersion: v6.3.0-rc1
dependencies:
  - name: lmutil
    repository: https://logicmonitor.github.io/helm-charts-qa
    # repository: file://../lmutil
    version: 0.1.6
