apiVersion: v2
description: Automated Kubernetes monitoring
icon: https://logicmonitor.github.io/helm-charts-qa/lm_logo.png
kubeVersion: '>= 1.16.0-0'
maintainers:
  - email: argus@logicmonitor.com
    name: LogicMonitor
name: argus
version: 3.3.0-rt01
home: https://logicmonitor.github.io/helm-charts-qa
appVersion: v8.3.0-rc2
