apiVersion: v2
name: lm-container
description: A Helm chart for Logicmonitor's Kubernetes monitoring solutions
type: application
version: 3.1.0-rc04
maintainers:
  - name: LogicMonitor
    email: argus@logicmonitor.com
icon: https://logicmonitor.github.io/helm-charts-qa/lm_logo.png
kubeVersion: ">= 1.16.0-0"
dependencies:
  - name: argus
    # need to explicitly quote to make it string, else json schema fails
    version: "5.1.0-rc03"
    repository: https://logicmonitor.github.io/helm-charts-qa
    # uncomment to test umbrella chart in while developing
    # repository: file://../argus
    condition: argus.enabled
    tags:
      - logicmonitor
      - argus
      - monitoring
  - name: collectorset-controller
    # need to explicitly quote to make it string, else json schema fails
    version: "4.1.0-rc04"
    repository: https://logicmonitor.github.io/helm-charts-qa
    # uncomment to test umbrella chart in while developing
    # repository: file://../collectorset-controller
    condition: collectorset-controller.enabled
    tags:
      - logicmonitor
      - collectorset-controller
      - monitoring
  - name: lm-logs
    # need to explicitly quote to make it string, else json schema fails
    version: "0.3.4-rc04"
    repository: https://logicmonitor.github.io/helm-charts-qa
    # uncomment to test umbrella chart in while developing
    # repository: file://../lm-logs
    condition: lm-logs.enabled
    tags:
      - logicmonitor
      - lm-logs
      - monitoring
      - pod-logs-collection
      - k8s-events-collection
  - condition: kube-state-metrics.enabled
    name: kube-state-metrics
    repository: https://prometheus-community.github.io/helm-charts
    version: 4.20.0
  - name: lmutil
    repository: https://logicmonitor.github.io/helm-charts-qa
    # uncomment to test umbrella chart in while developing
    # repository: file://../lmutil
    version: 0.1.1
