# Default values for lm-container.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  image:
    registry: ""
    pullPolicy: ""
  collectorsetServiceNameSuffix: "lm-container-collectorset-controller"

argus:
  enabled: true
collectorset-controller:
  enabled: true
