on: pull_request

jobs:
  apply-label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: get labels
        id: get_labels
        run: |
          labels=$(git diff --dirstat=files,0 main | egrep -o 'charts/(\w+\-?\w+)/' | cut -d'/' -f2 | uniq | tr '\n' ',' |  rev | cut -c2- | rev)
          echo "::set-output name=labels::$labels"
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.CHART_RELEASE_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: [${{ steps.get_labels.outputs.labels }}]
            })
