{{- if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "lm-otel-container.fullname" . }}-agent
  labels:
    {{- include "lm-otel-container.agent.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "lm-otel-container.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: otel-agent
  template:
    metadata:
      labels:
        {{- include "lm-otel-container.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: otel-agent
    spec:
      serviceAccountName: {{ include "lm-otel-container.serviceAccountName" . }}
      {{- with .Values.agent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.agent.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      containers:
        - name: otelcol
          image: {{ printf "%s:%s" .Values.agent.image.repository .Values.agent.image.tag | quote }}
          imagePullPolicy: {{ .Values.agent.image.pullPolicy }}
          args:
            - --config=/etc/otelcol-contrib/config.yaml
          env:
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: LM_BEARER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "lm-otel-container.secretName" . }}
                  key: {{ .Values.auth.secretKey }}
            {{- if and (eq .Values.clusterIdentity.mode "cloudAuto") .Values.clusterIdentity.fallbackClusterName }}
            - name: LM_CLUSTER_FALLBACK
              value: {{ .Values.clusterIdentity.fallbackClusterName | quote }}
            {{- end }}
          ports:
            - name: health
              containerPort: 13133
              protocol: TCP
          {{- with .Values.agent.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: otel-config
              mountPath: /etc/otelcol-contrib
              readOnly: true
      volumes:
        - name: otel-config
          configMap:
            name: {{ include "lm-otel-container.fullname" . }}-agent-otel-config
{{- end }}
