{{- if not .Values.auth.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lm-otel-container.secretName" . }}
  labels:
    {{- include "lm-otel-container.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.secretKey }}: {{ .Values.auth.bearerToken | quote }}
{{- end }}
